//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goatverse.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goatverse.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string globalAccept {
            get {
                return ResourceManager.GetString("globalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string globalAccount {
            get {
                return ResourceManager.GetString("globalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string globalAddFriend {
            get {
                return ResourceManager.GetString("globalAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string globalAttack {
            get {
                return ResourceManager.GetString("globalAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string globalBlocked {
            get {
                return ResourceManager.GetString("globalBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string globalCancel {
            get {
                return ResourceManager.GetString("globalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string globalCard {
            get {
                return ResourceManager.GetString("globalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Image.
        /// </summary>
        public static string globalChangeImage {
            get {
                return ResourceManager.GetString("globalChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string globalChangeLanguage {
            get {
                return ResourceManager.GetString("globalChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string globalClose {
            get {
                return ResourceManager.GetString("globalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Game.
        /// </summary>
        public static string globalCloseGame {
            get {
                return ResourceManager.GetString("globalCloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy lobby code.
        /// </summary>
        public static string globalCopyCode {
            get {
                return ResourceManager.GetString("globalCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string globalCreateAccount {
            get {
                return ResourceManager.GetString("globalCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Match.
        /// </summary>
        public static string globalCreateMatch {
            get {
                return ResourceManager.GetString("globalCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string globalDeck {
            get {
                return ResourceManager.GetString("globalDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Friend.
        /// </summary>
        public static string globalDeleteFriend {
            get {
                return ResourceManager.GetString("globalDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        public static string globalDeleteProfile {
            get {
                return ResourceManager.GetString("globalDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string globalDiscard {
            get {
                return ResourceManager.GetString("globalDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a Card.
        /// </summary>
        public static string globalDrawCard {
            get {
                return ResourceManager.GetString("globalDrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Pile.
        /// </summary>
        public static string globalDrawPile {
            get {
                return ResourceManager.GetString("globalDrawPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string globalDuel {
            get {
                return ResourceManager.GetString("globalDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string globalEditProfile {
            get {
                return ResourceManager.GetString("globalEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string globalEnglish {
            get {
                return ResourceManager.GetString("globalEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string globalExit {
            get {
                return ResourceManager.GetString("globalExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        public static string globalExitGame {
            get {
                return ResourceManager.GetString("globalExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string globalFriend {
            get {
                return ResourceManager.GetString("globalFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend List.
        /// </summary>
        public static string globalFriendList {
            get {
                return ResourceManager.GetString("globalFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string globalGuest {
            get {
                return ResourceManager.GetString("globalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string globalHistory {
            get {
                return ResourceManager.GetString("globalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play.
        /// </summary>
        public static string globalHowToPlay {
            get {
                return ResourceManager.GetString("globalHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Player.
        /// </summary>
        public static string globalInvitePlayer {
            get {
                return ResourceManager.GetString("globalInvitePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lobby.
        /// </summary>
        public static string globalJoinLobby {
            get {
                return ResourceManager.GetString("globalJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick Player.
        /// </summary>
        public static string globalKickPlayer {
            get {
                return ResourceManager.GetString("globalKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string globalLevel {
            get {
                return ResourceManager.GetString("globalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string globalLobby {
            get {
                return ResourceManager.GetString("globalLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Code.
        /// </summary>
        public static string globalLobbyCode {
            get {
                return ResourceManager.GetString("globalLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string globalLogIn {
            get {
                return ResourceManager.GetString("globalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose.
        /// </summary>
        public static string globalLoser {
            get {
                return ResourceManager.GetString("globalLoser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string globalMessages {
            get {
                return ResourceManager.GetString("globalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string globalNewPassword {
            get {
                return ResourceManager.GetString("globalNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string globalOldPassword {
            get {
                return ResourceManager.GetString("globalOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string globalPending {
            get {
                return ResourceManager.GetString("globalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Again.
        /// </summary>
        public static string globalPlayAgain {
            get {
                return ResourceManager.GetString("globalPlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play As Guest.
        /// </summary>
        public static string globalPlayAsGuest {
            get {
                return ResourceManager.GetString("globalPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string globalPlayer {
            get {
                return ResourceManager.GetString("globalPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string globalPoints {
            get {
                return ResourceManager.GetString("globalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string globalProfile {
            get {
                return ResourceManager.GetString("globalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string globalReturn {
            get {
                return ResourceManager.GetString("globalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string globalSaveChanges {
            get {
                return ResourceManager.GetString("globalSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        public static string globalSendFriendRequest {
            get {
                return ResourceManager.GetString("globalSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string globalSendMessage {
            get {
                return ResourceManager.GetString("globalSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string globalSpanish {
            get {
                return ResourceManager.GetString("globalSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string globalStartGame {
            get {
                return ResourceManager.GetString("globalStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string globalTrash {
            get {
                return ResourceManager.GetString("globalTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string globalTurn {
            get {
                return ResourceManager.GetString("globalTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string globalUser {
            get {
                return ResourceManager.GetString("globalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string globalWelcome {
            get {
                return ResourceManager.GetString("globalWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win.
        /// </summary>
        public static string globalWinner {
            get {
                return ResourceManager.GetString("globalWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are blocked by this user.
        /// </summary>
        public static string messageBlockedByUser {
            get {
                return ResourceManager.GetString("messageBlockedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your changes?.
        /// </summary>
        public static string messageConfirmChanges {
            get {
                return ResourceManager.GetString("messageConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server took too long to respond, try again later.
        /// </summary>
        public static string messageConnectionTookTooLong {
            get {
                return ResourceManager.GetString("messageConnectionTookTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already linked to an account.
        /// </summary>
        public static string messageEmailInUse {
            get {
                return ResourceManager.GetString("messageEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username already exists.
        /// </summary>
        public static string messageExistingUsername {
            get {
                return ResourceManager.GetString("messageExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game suffer and unexpected error. .
        /// </summary>
        public static string messageGameError {
            get {
                return ResourceManager.GetString("messageGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game requires a restart for the changes to make affect.
        /// </summary>
        public static string messageGamesRequiresRestart {
            get {
                return ResourceManager.GetString("messageGamesRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby you are trying to join doesn&apos;t exists.
        /// </summary>
        public static string messageLobbyNotExists {
            get {
                return ResourceManager.GetString("messageLobbyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner of the lobby can start the game.
        /// </summary>
        public static string messageLobbyOwnerStartGame {
            get {
                return ResourceManager.GetString("messageLobbyOwnerStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection required. Check your connection and try again..
        /// </summary>
        public static string messageLostInternetConnection {
            get {
                return ResourceManager.GetString("messageLostInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t exist, check and try again.
        /// </summary>
        public static string messageNotExistingUsername {
            get {
                return ResourceManager.GetString("messageNotExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t enter a valid email adress.
        /// </summary>
        public static string messageNotValidEmail {
            get {
                return ResourceManager.GetString("messageNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a lowercase letter, an uppercase letter, a number and a special character.
        /// </summary>
        public static string messageNotValidPassword {
            get {
                return ResourceManager.GetString("messageNotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game lost connection to the Server. Check your connection and try again later.
        /// </summary>
        public static string messageServerLostConnection {
            get {
                return ResourceManager.GetString("messageServerLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Sign In.
        /// </summary>
        public static string messageSuccessfulSignIn {
            get {
                return ResourceManager.GetString("messageSuccessfulSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has ocurred, if the problem persist contact customer support.
        /// </summary>
        public static string messageUnexpectedError {
            get {
                return ResourceManager.GetString("messageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string messageWrongPassword {
            get {
                return ResourceManager.GetString("messageWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rules 
        ///Building Your Set 
        ///There are 3 ways to build a set: 
        ///Having a matching pair of cards in your deck.
        ///Winning a duel.
        ///Duel 
        ///You may attack the top stack of an opponent&apos;s herd by producing a goat from your hand (or a wild card) that MATCHES the goat on top of the opponent&apos;s herd. If able, the opponent may choose to defend with an identical goat or a wild card (all wild cards are equally powerful, regardless of point value).
        ///Continue alternating until someone can no longer play or chooses not  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tutorialHowToPlay {
            get {
                return ResourceManager.GetString("tutorialHowToPlay", resourceCulture);
            }
        }
    }
}
