//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goatverse.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goatverse.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string globalAccept {
            get {
                return ResourceManager.GetString("globalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string globalAccount {
            get {
                return ResourceManager.GetString("globalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string globalAction {
            get {
                return ResourceManager.GetString("globalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string globalAddFriend {
            get {
                return ResourceManager.GetString("globalAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string globalAttack {
            get {
                return ResourceManager.GetString("globalAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string globalBlocked {
            get {
                return ResourceManager.GetString("globalBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string globalCancel {
            get {
                return ResourceManager.GetString("globalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string globalCard {
            get {
                return ResourceManager.GetString("globalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Image.
        /// </summary>
        public static string globalChangeImage {
            get {
                return ResourceManager.GetString("globalChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string globalChangeLanguage {
            get {
                return ResourceManager.GetString("globalChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string globalClose {
            get {
                return ResourceManager.GetString("globalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Game.
        /// </summary>
        public static string globalCloseGame {
            get {
                return ResourceManager.GetString("globalCloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy lobby code.
        /// </summary>
        public static string globalCopyCode {
            get {
                return ResourceManager.GetString("globalCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string globalCreateAccount {
            get {
                return ResourceManager.GetString("globalCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Match.
        /// </summary>
        public static string globalCreateMatch {
            get {
                return ResourceManager.GetString("globalCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string globalDeck {
            get {
                return ResourceManager.GetString("globalDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Friend.
        /// </summary>
        public static string globalDeleteFriend {
            get {
                return ResourceManager.GetString("globalDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        public static string globalDeleteProfile {
            get {
                return ResourceManager.GetString("globalDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string globalDiscard {
            get {
                return ResourceManager.GetString("globalDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a Card.
        /// </summary>
        public static string globalDrawCard {
            get {
                return ResourceManager.GetString("globalDrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Pile.
        /// </summary>
        public static string globalDrawPile {
            get {
                return ResourceManager.GetString("globalDrawPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string globalDuel {
            get {
                return ResourceManager.GetString("globalDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string globalEditProfile {
            get {
                return ResourceManager.GetString("globalEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string globalEnglish {
            get {
                return ResourceManager.GetString("globalEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string globalExit {
            get {
                return ResourceManager.GetString("globalExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        public static string globalExitGame {
            get {
                return ResourceManager.GetString("globalExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string globalFriend {
            get {
                return ResourceManager.GetString("globalFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend List.
        /// </summary>
        public static string globalFriendList {
            get {
                return ResourceManager.GetString("globalFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goats.
        /// </summary>
        public static string globalGoats {
            get {
                return ResourceManager.GetString("globalGoats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string globalGuest {
            get {
                return ResourceManager.GetString("globalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string globalHistory {
            get {
                return ResourceManager.GetString("globalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.T.A.-Goat Tactical Assault is an elite goat known for her cunning and strategic skills. Raised in the streets of his home, he joined a secret organization of expert tacticians, trained in stealth, driving, and combat. Armed with cutting-edge equipment, he infiltrates enemy territories, dismantling criminal operations and confronting rogue gangs. With an unstoppable style and a defiant attitude, G.T.A.-Goat is the nightmare of criminals, always one step ahead in his mission to restore order to his world..
        /// </summary>
        public static string globalHistoryG_T_A {
            get {
                return ResourceManager.GetString("globalHistoryG.T.A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just a goat..
        /// </summary>
        public static string globalHistoryGoat {
            get {
                return ResourceManager.GetString("globalHistoryGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goatink is a mysterious goat carrying an ancient legacy, marked by a grand destiny. With his green cloak and bow, she travels through forests, mountains, and forgotten ruins in search of magical artifacts to save his home. Guided by a supernatural force, he faces monsters, solves puzzles, and delves into forbidden places, unraveling the secrets of an ancient civilization. Goatink is more than a heroine; he is the hope that his word needs to restore lost balance..
        /// </summary>
        public static string globalHistoryGoatink {
            get {
                return ResourceManager.GetString("globalHistoryGoatink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goat Salvatore was born in a village destroyed by invaders. After losing everything, he swore revenge and trained in the art of stealth and strategy. Donning a woolen goat cape and wielding a forged knife, he infiltrated enemy ranks, dismantling their plans. Now, he moves in the shadows, protecting the innocent and ensuring his people’s secrets never fall into the wrong hands..
        /// </summary>
        public static string globalHistoryGoatSalvatore {
            get {
                return ResourceManager.GetString("globalHistoryGoatSalvatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goat Slayer is an unstoppable goat, forged in the fight against the dark forces threatening his home. Armed with sharp horns and relentless fury, he battles monsters and infernal creatures emerging from the depths of the world. Each battle makes him stronger, and his name has become a legend among those fighting the shadows. No enemy can stop him..
        /// </summary>
        public static string globalHistoryGoatSlayer {
            get {
                return ResourceManager.GetString("globalHistoryGoatSlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goatzzz is an explosive goat born in the depths of Capraterra’s caves. Her body, covered in strange energy, glows in the dark as she sneaks toward her target. With every step, her tension builds until, at the least expected moment, she explodes in a massive detonation! With her fixed gaze and silent stride, Goatzzz lurks in the corners of the world, ready to destroy everything in her path, leaving a trail of chaos behind. No one knows when or where she will strike, but everyone knows her explosion will be d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string globalHistoryGoatzzz {
            get {
                return ResourceManager.GetString("globalHistoryGoatzzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Goat is a legendary goat, forged in battle and designed to protect his home. Raised in a world ravaged by invaders, she joined a secret program that transformed her into an unstoppable warrior. With advanced armor and horns sharp as a sword, Master Goat leads her herd against the dark forces, facing colossal creatures and monsters on the battlefield. Her presence is a beacon of hope, and her mission is clear: save her home from total destruction, no matter the cost..
        /// </summary>
        public static string globalHistoryMasterGoat {
            get {
                return ResourceManager.GetString("globalHistoryMasterGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notpac-Goat got lost in a magical maze, chased by shadows. But instead of running, it began devouring everything in its path, gaining strength with each step. Now it races through the corridors, escaping and destroying whatever crosses its way, its light growing with every victory..
        /// </summary>
        public static string globalHistoryNotpacGoat {
            get {
                return ResourceManager.GetString("globalHistoryNotpacGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumber Goat is a plumbing expert goat, renowned for her ability to solve the most complicated pipe problems in her city. With her toolbox and skill, she ventures into the darkest tunnels and ducts, fixing leaks, unclogging drains, and facing aquatic creatures lurking in the sewers. Always with a smile and her plumber’s cap, Pumber Goat keeps Capraterra’s flow running, tackling every challenge with ingenuity and bravery..
        /// </summary>
        public static string globalHistoryPlumberGoat {
            get {
                return ResourceManager.GetString("globalHistoryPlumberGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play.
        /// </summary>
        public static string globalHowToPlay {
            get {
                return ResourceManager.GetString("globalHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Player.
        /// </summary>
        public static string globalInvitePlayer {
            get {
                return ResourceManager.GetString("globalInvitePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lobby.
        /// </summary>
        public static string globalJoinLobby {
            get {
                return ResourceManager.GetString("globalJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick Player.
        /// </summary>
        public static string globalKickPlayer {
            get {
                return ResourceManager.GetString("globalKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string globalLevel {
            get {
                return ResourceManager.GetString("globalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string globalLobby {
            get {
                return ResourceManager.GetString("globalLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Code.
        /// </summary>
        public static string globalLobbyCode {
            get {
                return ResourceManager.GetString("globalLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string globalLogIn {
            get {
                return ResourceManager.GetString("globalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose.
        /// </summary>
        public static string globalLoser {
            get {
                return ResourceManager.GetString("globalLoser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string globalMessages {
            get {
                return ResourceManager.GetString("globalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string globalNewPassword {
            get {
                return ResourceManager.GetString("globalNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string globalOldPassword {
            get {
                return ResourceManager.GetString("globalOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string globalPending {
            get {
                return ResourceManager.GetString("globalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Again.
        /// </summary>
        public static string globalPlayAgain {
            get {
                return ResourceManager.GetString("globalPlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play As Guest.
        /// </summary>
        public static string globalPlayAsGuest {
            get {
                return ResourceManager.GetString("globalPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string globalPlayer {
            get {
                return ResourceManager.GetString("globalPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string globalPoints {
            get {
                return ResourceManager.GetString("globalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string globalProfile {
            get {
                return ResourceManager.GetString("globalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Games (last 10).
        /// </summary>
        public static string globalRecentMatches {
            get {
                return ResourceManager.GetString("globalRecentMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string globalReturn {
            get {
                return ResourceManager.GetString("globalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string globalSaveChanges {
            get {
                return ResourceManager.GetString("globalSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        public static string globalSendFriendRequest {
            get {
                return ResourceManager.GetString("globalSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string globalSendMessage {
            get {
                return ResourceManager.GetString("globalSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string globalSpanish {
            get {
                return ResourceManager.GetString("globalSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string globalStartGame {
            get {
                return ResourceManager.GetString("globalStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string globalStatistics {
            get {
                return ResourceManager.GetString("globalStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string globalTrash {
            get {
                return ResourceManager.GetString("globalTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string globalTurn {
            get {
                return ResourceManager.GetString("globalTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string globalUser {
            get {
                return ResourceManager.GetString("globalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string globalWelcome {
            get {
                return ResourceManager.GetString("globalWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild.
        /// </summary>
        public static string globalWild {
            get {
                return ResourceManager.GetString("globalWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win.
        /// </summary>
        public static string globalWinner {
            get {
                return ResourceManager.GetString("globalWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a single card to attack..
        /// </summary>
        public static string messageAttackCard {
            get {
                return ResourceManager.GetString("messageAttackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are blocked by this user.
        /// </summary>
        public static string messageBlockedByUser {
            get {
                return ResourceManager.GetString("messageBlockedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your changes?.
        /// </summary>
        public static string messageConfirmChanges {
            get {
                return ResourceManager.GetString("messageConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server took too long to respond, try again later.
        /// </summary>
        public static string messageConnectionTookTooLong {
            get {
                return ResourceManager.GetString("messageConnectionTookTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a single card to discard..
        /// </summary>
        public static string messageDiscardCard {
            get {
                return ResourceManager.GetString("messageDiscardCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already linked to an account.
        /// </summary>
        public static string messageEmailInUse {
            get {
                return ResourceManager.GetString("messageEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username already exists.
        /// </summary>
        public static string messageExistingUsername {
            get {
                return ResourceManager.GetString("messageExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game suffer and unexpected error. .
        /// </summary>
        public static string messageGameError {
            get {
                return ResourceManager.GetString("messageGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game requires a restart for the changes to make affect.
        /// </summary>
        public static string messageGamesRequiresRestart {
            get {
                return ResourceManager.GetString("messageGamesRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby you are trying to join doesn&apos;t exists.
        /// </summary>
        public static string messageLobbyNotExists {
            get {
                return ResourceManager.GetString("messageLobbyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner of the lobby can start the game.
        /// </summary>
        public static string messageLobbyOwnerStartGame {
            get {
                return ResourceManager.GetString("messageLobbyOwnerStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection required. Check your connection and try again..
        /// </summary>
        public static string messageLostInternetConnection {
            get {
                return ResourceManager.GetString("messageLostInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t exist, check and try again.
        /// </summary>
        public static string messageNotExistingUsername {
            get {
                return ResourceManager.GetString("messageNotExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t enter a valid email adress.
        /// </summary>
        public static string messageNotValidEmail {
            get {
                return ResourceManager.GetString("messageNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a lowercase letter, an uppercase letter, a number and a special character.
        /// </summary>
        public static string messageNotValidPassword {
            get {
                return ResourceManager.GetString("messageNotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game lost connection to the Server. Check your connection and try again later.
        /// </summary>
        public static string messageServerLostConnection {
            get {
                return ResourceManager.GetString("messageServerLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Sign In.
        /// </summary>
        public static string messageSuccessfulSignIn {
            get {
                return ResourceManager.GetString("messageSuccessfulSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has ocurred, if the problem persist contact customer support.
        /// </summary>
        public static string messageUnexpectedError {
            get {
                return ResourceManager.GetString("messageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string messageWrongPassword {
            get {
                return ResourceManager.GetString("messageWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rules 
        ///Building Your Set 
        ///There are 3 ways to build a set: 
        ///Having a matching pair of cards in your deck.
        ///Winning a duel.
        ///Duel 
        ///You may attack the top stack of an opponent&apos;s herd by producing a goat from your hand (or a wild card) that MATCHES the goat on top of the opponent&apos;s herd. If able, the opponent may choose to defend with an identical goat or a wild card (all wild cards are equally powerful, regardless of point value).
        ///Continue alternating until someone can no longer play or chooses not  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tutorialHowToPlay {
            get {
                return ResourceManager.GetString("tutorialHowToPlay", resourceCulture);
            }
        }
    }
}
