//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goatverse.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goatverse.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string globalAccept {
            get {
                return ResourceManager.GetString("globalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string globalAccount {
            get {
                return ResourceManager.GetString("globalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        public static string globalAction {
            get {
                return ResourceManager.GetString("globalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string globalAddFriend {
            get {
                return ResourceManager.GetString("globalAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attack.
        /// </summary>
        public static string globalAttack {
            get {
                return ResourceManager.GetString("globalAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked.
        /// </summary>
        public static string globalBlocked {
            get {
                return ResourceManager.GetString("globalBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string globalCancel {
            get {
                return ResourceManager.GetString("globalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card.
        /// </summary>
        public static string globalCard {
            get {
                return ResourceManager.GetString("globalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Profile Image.
        /// </summary>
        public static string globalChangeImage {
            get {
                return ResourceManager.GetString("globalChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        public static string globalChangeLanguage {
            get {
                return ResourceManager.GetString("globalChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string globalClose {
            get {
                return ResourceManager.GetString("globalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Game.
        /// </summary>
        public static string globalCloseGame {
            get {
                return ResourceManager.GetString("globalCloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy lobby code.
        /// </summary>
        public static string globalCopyCode {
            get {
                return ResourceManager.GetString("globalCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Account.
        /// </summary>
        public static string globalCreateAccount {
            get {
                return ResourceManager.GetString("globalCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Match.
        /// </summary>
        public static string globalCreateMatch {
            get {
                return ResourceManager.GetString("globalCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deck.
        /// </summary>
        public static string globalDeck {
            get {
                return ResourceManager.GetString("globalDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Friend.
        /// </summary>
        public static string globalDeleteFriend {
            get {
                return ResourceManager.GetString("globalDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Profile.
        /// </summary>
        public static string globalDeleteProfile {
            get {
                return ResourceManager.GetString("globalDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discard.
        /// </summary>
        public static string globalDiscard {
            get {
                return ResourceManager.GetString("globalDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw a Card.
        /// </summary>
        public static string globalDrawCard {
            get {
                return ResourceManager.GetString("globalDrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Pile.
        /// </summary>
        public static string globalDrawPile {
            get {
                return ResourceManager.GetString("globalDrawPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duel.
        /// </summary>
        public static string globalDuel {
            get {
                return ResourceManager.GetString("globalDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string globalEditProfile {
            get {
                return ResourceManager.GetString("globalEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string globalEnglish {
            get {
                return ResourceManager.GetString("globalEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string globalExit {
            get {
                return ResourceManager.GetString("globalExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Game.
        /// </summary>
        public static string globalExitGame {
            get {
                return ResourceManager.GetString("globalExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string globalFriend {
            get {
                return ResourceManager.GetString("globalFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend List.
        /// </summary>
        public static string globalFriendList {
            get {
                return ResourceManager.GetString("globalFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goats.
        /// </summary>
        public static string globalGoats {
            get {
                return ResourceManager.GetString("globalGoats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string globalGuest {
            get {
                return ResourceManager.GetString("globalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        public static string globalHistory {
            get {
                return ResourceManager.GetString("globalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a G.T.A.-Goat Tactical Assault is an elite goat known for her cunning and strategic skills. Raised in the streets of his home, he joined a secret organization of expert tacticians, trained in stealth, driving, and combat. Armed with cutting-edge equipment, he infiltrates enemy territories, dismantling criminal operations and confronting rogue gangs. With an unstoppable style and a defiant attitude, G.T.A.-Goat is the nightmare of criminals, always one step ahead in his mission to restore order to his world..
        /// </summary>
        public static string globalHistoryG_T_A {
            get {
                return ResourceManager.GetString("globalHistoryG.T.A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s just a goat..
        /// </summary>
        public static string globalHistoryGoat {
            get {
                return ResourceManager.GetString("globalHistoryGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goatink is a mysterious goat carrying an ancient legacy, marked by a grand destiny. With his green cloak and bow, she travels through forests, mountains, and forgotten ruins in search of magical artifacts to save his home. Guided by a supernatural force, he faces monsters, solves puzzles, and delves into forbidden places, unraveling the secrets of an ancient civilization. Goatink is more than a heroine; he is the hope that his word needs to restore lost balance..
        /// </summary>
        public static string globalHistoryGoatink {
            get {
                return ResourceManager.GetString("globalHistoryGoatink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goat Salvatore was born in a village destroyed by invaders. After losing everything, he swore revenge and trained in the art of stealth and strategy. Donning a woolen goat cape and wielding a forged knife, he infiltrated enemy ranks, dismantling their plans. Now, he moves in the shadows, protecting the innocent and ensuring his people’s secrets never fall into the wrong hands..
        /// </summary>
        public static string globalHistoryGoatSalvatore {
            get {
                return ResourceManager.GetString("globalHistoryGoatSalvatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goat Slayer is an unstoppable goat, forged in the fight against the dark forces threatening his home. Armed with sharp horns and relentless fury, he battles monsters and infernal creatures emerging from the depths of the world. Each battle makes him stronger, and his name has become a legend among those fighting the shadows. No enemy can stop him..
        /// </summary>
        public static string globalHistoryGoatSlayer {
            get {
                return ResourceManager.GetString("globalHistoryGoatSlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goatzzz is an explosive goat born in the depths of Capraterra’s caves. Her body, covered in strange energy, glows in the dark as she sneaks toward her target. With every step, her tension builds until, at the least expected moment, she explodes in a massive detonation! With her fixed gaze and silent stride, Goatzzz lurks in the corners of the world, ready to destroy everything in her path, leaving a trail of chaos behind. No one knows when or where she will strike, but everyone knows her explosion will be d [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string globalHistoryGoatzzz {
            get {
                return ResourceManager.GetString("globalHistoryGoatzzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Goat is a legendary goat, forged in battle and designed to protect his home. Raised in a world ravaged by invaders, she joined a secret program that transformed her into an unstoppable warrior. With advanced armor and horns sharp as a sword, Master Goat leads her herd against the dark forces, facing colossal creatures and monsters on the battlefield. Her presence is a beacon of hope, and her mission is clear: save her home from total destruction, no matter the cost..
        /// </summary>
        public static string globalHistoryMasterGoat {
            get {
                return ResourceManager.GetString("globalHistoryMasterGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notpac-Goat got lost in a magical maze, chased by shadows. But instead of running, it began devouring everything in its path, gaining strength with each step. Now it races through the corridors, escaping and destroying whatever crosses its way, its light growing with every victory..
        /// </summary>
        public static string globalHistoryNotpacGoat {
            get {
                return ResourceManager.GetString("globalHistoryNotpacGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pumber Goat is a plumbing expert goat, renowned for her ability to solve the most complicated pipe problems in her city. With her toolbox and skill, she ventures into the darkest tunnels and ducts, fixing leaks, unclogging drains, and facing aquatic creatures lurking in the sewers. Always with a smile and her plumber’s cap, Pumber Goat keeps Capraterra’s flow running, tackling every challenge with ingenuity and bravery..
        /// </summary>
        public static string globalHistoryPlumberGoat {
            get {
                return ResourceManager.GetString("globalHistoryPlumberGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to play.
        /// </summary>
        public static string globalHowToPlay {
            get {
                return ResourceManager.GetString("globalHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Player.
        /// </summary>
        public static string globalInvitePlayer {
            get {
                return ResourceManager.GetString("globalInvitePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Lobby.
        /// </summary>
        public static string globalJoinLobby {
            get {
                return ResourceManager.GetString("globalJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick Player.
        /// </summary>
        public static string globalKickPlayer {
            get {
                return ResourceManager.GetString("globalKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Level.
        /// </summary>
        public static string globalLevel {
            get {
                return ResourceManager.GetString("globalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string globalLobby {
            get {
                return ResourceManager.GetString("globalLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby Code.
        /// </summary>
        public static string globalLobbyCode {
            get {
                return ResourceManager.GetString("globalLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string globalLogIn {
            get {
                return ResourceManager.GetString("globalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You lose.
        /// </summary>
        public static string globalLoser {
            get {
                return ResourceManager.GetString("globalLoser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messages.
        /// </summary>
        public static string globalMessages {
            get {
                return ResourceManager.GetString("globalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string globalNewPassword {
            get {
                return ResourceManager.GetString("globalNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old Password.
        /// </summary>
        public static string globalOldPassword {
            get {
                return ResourceManager.GetString("globalOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string globalPending {
            get {
                return ResourceManager.GetString("globalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Again.
        /// </summary>
        public static string globalPlayAgain {
            get {
                return ResourceManager.GetString("globalPlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play As Guest.
        /// </summary>
        public static string globalPlayAsGuest {
            get {
                return ResourceManager.GetString("globalPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string globalPlayer {
            get {
                return ResourceManager.GetString("globalPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string globalPoints {
            get {
                return ResourceManager.GetString("globalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string globalProfile {
            get {
                return ResourceManager.GetString("globalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent Games (last 10).
        /// </summary>
        public static string globalRecentMatches {
            get {
                return ResourceManager.GetString("globalRecentMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string globalReturn {
            get {
                return ResourceManager.GetString("globalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string globalSaveChanges {
            get {
                return ResourceManager.GetString("globalSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Friend Request.
        /// </summary>
        public static string globalSendFriendRequest {
            get {
                return ResourceManager.GetString("globalSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Message.
        /// </summary>
        public static string globalSendMessage {
            get {
                return ResourceManager.GetString("globalSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string globalSpanish {
            get {
                return ResourceManager.GetString("globalSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string globalStartGame {
            get {
                return ResourceManager.GetString("globalStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        public static string globalStatistics {
            get {
                return ResourceManager.GetString("globalStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trash.
        /// </summary>
        public static string globalTrash {
            get {
                return ResourceManager.GetString("globalTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn.
        /// </summary>
        public static string globalTurn {
            get {
                return ResourceManager.GetString("globalTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string globalUser {
            get {
                return ResourceManager.GetString("globalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string globalWelcome {
            get {
                return ResourceManager.GetString("globalWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wild.
        /// </summary>
        public static string globalWild {
            get {
                return ResourceManager.GetString("globalWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You win.
        /// </summary>
        public static string globalWinner {
            get {
                return ResourceManager.GetString("globalWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string globalWins {
            get {
                return ResourceManager.GetString("globalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a single card to attack..
        /// </summary>
        public static string messageAttackCard {
            get {
                return ResourceManager.GetString("messageAttackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are blocked by this user.
        /// </summary>
        public static string messageBlockedByUser {
            get {
                return ResourceManager.GetString("messageBlockedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your changes?.
        /// </summary>
        public static string messageConfirmChanges {
            get {
                return ResourceManager.GetString("messageConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Server took too long to respond, try again later.
        /// </summary>
        public static string messageConnectionTookTooLong {
            get {
                return ResourceManager.GetString("messageConnectionTookTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a single card to discard..
        /// </summary>
        public static string messageDiscardCard {
            get {
                return ResourceManager.GetString("messageDiscardCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already linked to an account.
        /// </summary>
        public static string messageEmailInUse {
            get {
                return ResourceManager.GetString("messageEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That username already exists.
        /// </summary>
        public static string messageExistingUsername {
            get {
                return ResourceManager.GetString("messageExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game suffer and unexpected error. .
        /// </summary>
        public static string messageGameError {
            get {
                return ResourceManager.GetString("messageGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game requires a restart for the changes to make affect.
        /// </summary>
        public static string messageGamesRequiresRestart {
            get {
                return ResourceManager.GetString("messageGamesRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby you are trying to join doesn&apos;t exists.
        /// </summary>
        public static string messageLobbyNotExists {
            get {
                return ResourceManager.GetString("messageLobbyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the owner of the lobby can start the game.
        /// </summary>
        public static string messageLobbyOwnerStartGame {
            get {
                return ResourceManager.GetString("messageLobbyOwnerStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internet connection required. Check your connection and try again..
        /// </summary>
        public static string messageLostInternetConnection {
            get {
                return ResourceManager.GetString("messageLostInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user doesn&apos;t exist, check and try again.
        /// </summary>
        public static string messageNotExistingUsername {
            get {
                return ResourceManager.GetString("messageNotExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t enter a valid email adress.
        /// </summary>
        public static string messageNotValidEmail {
            get {
                return ResourceManager.GetString("messageNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password requires a lowercase letter, an uppercase letter, a number and a special character.
        /// </summary>
        public static string messageNotValidPassword {
            get {
                return ResourceManager.GetString("messageNotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game lost connection to the Server. Check your connection and try again later.
        /// </summary>
        public static string messageServerLostConnection {
            get {
                return ResourceManager.GetString("messageServerLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful Sign In.
        /// </summary>
        public static string messageSuccessfulSignIn {
            get {
                return ResourceManager.GetString("messageSuccessfulSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error has ocurred, if the problem persist contact customer support.
        /// </summary>
        public static string messageUnexpectedError {
            get {
                return ResourceManager.GetString("messageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is incorrect.
        /// </summary>
        public static string messageWrongPassword {
            get {
                return ResourceManager.GetString("messageWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Rules 
        ///Building Your Set 
        ///There are 3 ways to build a set: 
        ///Having a matching pair of cards in your deck.
        ///Winning a duel.
        ///Duel 
        ///You may attack the top stack of an opponent&apos;s herd by producing a goat from your hand (or a wild card) that MATCHES the goat on top of the opponent&apos;s herd. If able, the opponent may choose to defend with an identical goat or a wild card (all wild cards are equally powerful, regardless of point value).
        ///Continue alternating until someone can no longer play or chooses not  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string tutorialHowToPlay {
            get {
                return ResourceManager.GetString("tutorialHowToPlay", resourceCulture);
            }
        }
    }
}
